### PR TITLE
Automated Testing

### LINKED ISSUE #9: Run automated test in CI, similar to last year
Last year we had an automated test which ensured there wasn't a crash on startup, in autonomous, or when disabled. Having that again would be useful, especially at this stage when the project hasn't stabilized yet.

PR for reference:  https://github.com/robototes/RapidReact2022/pull/43

### PR DESCRIPTION
**Pull request by KangarooKoala**
Resolves #9
Same as last year, the test is run with `./gradlew simulateJavaDebug -PautomatedTest=true`, and the CI action is set up to run it on pushes and pull requests. The `automatedTest` property changes the main class to `AutomatedTestMain`, which runs `AutomatedTestRobot` instead of `Robot`.
The test runs in a separate thread that manages the robot state with `DriverStationDataJNI`, with these steps (same as last year):
1. Wait two seconds
2. Set mode to autonomous and enable robot
3. Wait ten seconds
4. Disable the robot
5. Wait two seconds
6. End the competition, which exits the program

Unhandled Java exceptions are caught and logged before exiting the program with a failure result that causes the gradle task to fail with an error.

### CODE REVIEW

**Comment by KangarooKoala** [comment]
I moved the testing code into `AutomatedTestRobot` simply because I thought it was better architecture to have the testing code be separate from what's being tested. Ideally the testing code could all be moved into `AutomatedTestMain`, but I don't think that's possible (We need to intercept exceptions raised during `startCompetition` before they get suppressed, also getting the timing right for managing the robot state would be difficult).

**Comment by KangarooKoala** [comment]
Also, I'm not sure why we were waiting for two seconds after intercepting an exception, so I commented it out- If @jamesdooley4 could explain why that was added that'd be great. (The commit message for when it was added just said "Move crash to intake subsystem and add some logging", but I haven't seen any effects on either of those)

**Comment by jamesdooley4** [comment]
> 

My guess is the wait was to give time for the simulation HAL to capture the callstack message (sent via `HAL.sendError(isError, code, false, error, locString, traceString.toString(), true);` before the process exits and tears down simulation. As long as you've verified an unhandled exception (such as null pointer access) still generates a valid callstack in the CI test, I'm good with removing the sleep.

File: src/main/java/frc/team2412/robot/test/AutomatedTestRobot.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+			Throwable cause = throwable.getCause();
+			if (cause != null) {
+				throwable = cause;
+			}
+			DriverStation.reportError(
+					"Unhandled exception: " + throwable.toString(), throwable.getStackTrace());
+			// Sleep was added to original code in
+			// https://github.com/robototes/RapidReact2022/pull/43/commits/e9e81bcae76dabe08b6f2d24eb56b55378012565
+			// sleep(2000);
+			System.exit(-1);
```
Comment (jamesdooley4) [inline src/main/java/frc/team2412/robot/test/AutomatedTestRobot.java:41]: Please confirm you've verified that throwing an unhandled exception still causes a callstack to show up in the CI output. Pushing a commit with something set to `null`, running the CI tests, and then undoing that commit should be sufficient.

**Review by jamesdooley4 — APPROVED** [review]

File: src/main/java/frc/team2412/robot/test/AutomatedTestRobot.java (hunk 1 above)
Comment (KangarooKoala) [reply src/main/java/frc/team2412/robot/test/AutomatedTestRobot.java:41]: I've tested behavior locally with `./gradlew simulateJava -PautomatedTest=true` (`simulateJavaDebug` doesn't work on school laptops), but it would be valuable to use the commit method.

Comment (obj-obj) [reply src/main/java/frc/team2412/robot/test/AutomatedTestRobot.java:41]: The log in CI is exactly the same as running it on your own system so I don't think it's really needed

Comment (KangarooKoala) [reply src/main/java/frc/team2412/robot/test/AutomatedTestRobot.java:41]: I'll still do them so that people could see the exact results, but yeah I don't expect it to be different from locally (unless `simulateJava` has some odd differences with `simulateJavaDebug`).

**Review by jamesdooley4 — APPROVED** [review]

**Review by TAKBS2412 — APPROVED** [review]

**Review by jbko6 — APPROVED** [review]
